name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: "1.15.6" # Define the elixir version [required]
          otp-version: "26.1" # Define the OTP version [required]

      - name: Install Dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
        